# TCL File Generated by Component Editor 16.0
# Tue Nov 07 11:45:22 CST 2017
# DO NOT MODIFY


# 
# pwm "Avalon PWM Peripheral" v1.0
# Martin Garaj 2017.11.07.11:45:22
# PWM peripheral with software adjustible prescaler, period, duty and blank. Can generate up to 16 independet outputs (only presclaler is shared).
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module pwm
# 
set_module_property DESCRIPTION "PWM peripheral with software adjustible prescaler, period, duty and blank. Can generate up to 16 independet outputs (only presclaler is shared)."
set_module_property NAME pwm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Martin Garaj"
set_module_property DISPLAY_NAME "Avalon PWM Peripheral"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_PWM
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_PWM.vhd VHDL PATH source_files/avalon_pwm/avalon_PWM.vhd TOP_LEVEL_FILE
add_fileset_file avalon_PWM.vhd.bak OTHER PATH source_files/avalon_pwm/avalon_PWM.vhd.bak
add_fileset_file package_avalon_PWM.vhd VHDL PATH source_files/avalon_pwm/package_avalon_PWM.vhd
add_fileset_file package_avalon_PWM.vhd.bak OTHER PATH source_files/avalon_pwm/package_avalon_PWM.vhd.bak
add_fileset_file package_common.vhd VHDL PATH source_files/avalon_pwm/package_common.vhd
add_fileset_file pwm_counter_blank.vhd VHDL PATH source_files/avalon_pwm/pwm_counter_blank.vhd
add_fileset_file soft_prescaler.vhd VHDL PATH source_files/avalon_pwm/soft_prescaler.vhd
add_fileset_file output_buffer.cmp OTHER PATH source_files/avalon_pwm/output_buffer/output_buffer.cmp
add_fileset_file output_buffer.qip OTHER PATH source_files/avalon_pwm/output_buffer/output_buffer.qip
add_fileset_file output_buffer.vhd VHDL PATH source_files/avalon_pwm/output_buffer/output_buffer.vhd


# 
# parameters
# 
add_parameter QUANTITY INTEGER 10 "Number of PWM outputs \[1...16]"
set_parameter_property QUANTITY DEFAULT_VALUE 10
set_parameter_property QUANTITY DISPLAY_NAME QUANTITY
set_parameter_property QUANTITY TYPE INTEGER
set_parameter_property QUANTITY UNITS None
set_parameter_property QUANTITY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property QUANTITY DESCRIPTION "Number of PWM outputs \[1...16]"
set_parameter_property QUANTITY HDL_PARAMETER true
add_parameter PRESCALER_COUNTER_LENGTH INTEGER 8 "Number of presclaler counter bits \[1...32]"
set_parameter_property PRESCALER_COUNTER_LENGTH DEFAULT_VALUE 8
set_parameter_property PRESCALER_COUNTER_LENGTH DISPLAY_NAME PRESCALER_COUNTER_LENGTH
set_parameter_property PRESCALER_COUNTER_LENGTH TYPE INTEGER
set_parameter_property PRESCALER_COUNTER_LENGTH UNITS None
set_parameter_property PRESCALER_COUNTER_LENGTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PRESCALER_COUNTER_LENGTH DESCRIPTION "Number of presclaler counter bits \[1...32]"
set_parameter_property PRESCALER_COUNTER_LENGTH HDL_PARAMETER true
add_parameter PWM_COUNTER_LENGTH INTEGER 14 "Number of PWM counter bits \[1...32]"
set_parameter_property PWM_COUNTER_LENGTH DEFAULT_VALUE 14
set_parameter_property PWM_COUNTER_LENGTH DISPLAY_NAME PWM_COUNTER_LENGTH
set_parameter_property PWM_COUNTER_LENGTH TYPE INTEGER
set_parameter_property PWM_COUNTER_LENGTH UNITS None
set_parameter_property PWM_COUNTER_LENGTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PWM_COUNTER_LENGTH DESCRIPTION "Number of PWM counter bits \[1...32]"
set_parameter_property PWM_COUNTER_LENGTH HDL_PARAMETER true
add_parameter BLANK_COUNTER_LENGTH INTEGER 6 "Number of blank counter bits \[1...32]"
set_parameter_property BLANK_COUNTER_LENGTH DEFAULT_VALUE 6
set_parameter_property BLANK_COUNTER_LENGTH DISPLAY_NAME BLANK_COUNTER_LENGTH
set_parameter_property BLANK_COUNTER_LENGTH TYPE INTEGER
set_parameter_property BLANK_COUNTER_LENGTH UNITS None
set_parameter_property BLANK_COUNTER_LENGTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BLANK_COUNTER_LENGTH DESCRIPTION "Number of blank counter bits \[1...32]"
set_parameter_property BLANK_COUNTER_LENGTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point output
# 
add_interface output conduit end
set_interface_property output associatedClock clk
set_interface_property output associatedReset rst
set_interface_property output ENABLED true
set_interface_property output EXPORT_OF ""
set_interface_property output PORT_NAME_MAP ""
set_interface_property output CMSIS_SVD_VARIABLES ""
set_interface_property output SVD_ADDRESS_GROUP ""

add_interface_port output pwm_out external Output quantity


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point s1_1
# 
add_interface s1_1 avalon end
set_interface_property s1_1 addressUnits WORDS
set_interface_property s1_1 associatedClock clk
set_interface_property s1_1 associatedReset rst
set_interface_property s1_1 bitsPerSymbol 8
set_interface_property s1_1 burstOnBurstBoundariesOnly false
set_interface_property s1_1 burstcountUnits WORDS
set_interface_property s1_1 explicitAddressSpan 0
set_interface_property s1_1 holdTime 0
set_interface_property s1_1 linewrapBursts false
set_interface_property s1_1 maximumPendingReadTransactions 0
set_interface_property s1_1 maximumPendingWriteTransactions 0
set_interface_property s1_1 readLatency 0
set_interface_property s1_1 readWaitTime 1
set_interface_property s1_1 setupTime 0
set_interface_property s1_1 timingUnits Cycles
set_interface_property s1_1 writeWaitTime 0
set_interface_property s1_1 ENABLED true
set_interface_property s1_1 EXPORT_OF ""
set_interface_property s1_1 PORT_NAME_MAP ""
set_interface_property s1_1 CMSIS_SVD_VARIABLES ""
set_interface_property s1_1 SVD_ADDRESS_GROUP ""

add_interface_port s1_1 AB address Input 6
add_interface_port s1_1 DBin writedata Input 32
add_interface_port s1_1 DBout readdata Output 32
add_interface_port s1_1 wr write Input 1
add_interface_port s1_1 rd read Input 1
set_interface_assignment s1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1_1 embeddedsw.configuration.isPrintableDevice 0

