# TCL File Generated by Component Editor 16.0
# Tue Mar 28 14:10:04 CST 2017
# DO NOT MODIFY


# 
# i2c "i2c Master Peripheral" v1.0
# Martin Garaj 2017.03.28.14:10:04
# i2c master IP core with avalon interface
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module i2c
# 
set_module_property DESCRIPTION "i2c master IP core with avalon interface"
set_module_property NAME i2c
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Martin Garaj"
set_module_property DISPLAY_NAME "i2c Master Peripheral"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_i2c_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_i2c_master.vhd VHDL PATH source_files/avalon_i2c_master/avalon_i2c_master.vhd TOP_LEVEL_FILE
add_fileset_file i2c_master_bit_ctrl.vhd VHDL PATH source_files/avalon_i2c_master/i2c_master_bit_ctrl.vhd
add_fileset_file i2c_master_byte_ctrl.vhd VHDL PATH source_files/avalon_i2c_master/i2c_master_byte_ctrl.vhd
add_fileset_file i2c_master_top.vhd VHDL PATH source_files/avalon_i2c_master/i2c_master_top.vhd
add_fileset_file tristate_buffer.vhd VHDL PATH source_files/tristate_buffer/tristate_buffer.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 AB address Input 3
add_interface_port s1 DBin writedata Input 32
add_interface_port s1 DBout readdata Output 32
add_interface_port s1 wr write Input 1
add_interface_port s1 rd read Input 1
add_interface_port s1 wrq waitrequest Output 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point sda
# 
add_interface sda conduit end
set_interface_property sda associatedClock clock
set_interface_property sda associatedReset reset
set_interface_property sda ENABLED true
set_interface_property sda EXPORT_OF ""
set_interface_property sda PORT_NAME_MAP ""
set_interface_property sda CMSIS_SVD_VARIABLES ""
set_interface_property sda SVD_ADDRESS_GROUP ""

add_interface_port sda sda export Bidir 1


# 
# connection point scl
# 
add_interface scl conduit end
set_interface_property scl associatedClock clock
set_interface_property scl associatedReset ""
set_interface_property scl ENABLED true
set_interface_property scl EXPORT_OF ""
set_interface_property scl PORT_NAME_MAP ""
set_interface_property scl CMSIS_SVD_VARIABLES ""
set_interface_property scl SVD_ADDRESS_GROUP ""

add_interface_port scl scl export Bidir 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock clock
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1

